### ISSUE TITLE
ChatGPT client for all platforms and library for Delphi 

### ISSUE THREAD

**Issue by HemulGM** [taishi-i/awesome-ChatGPT-repositories#8]
https://github.com/HemulGM/DelphiOpenAI
https://github.com/HemulGM/ChatGPT

**Comment by taishi-i** [comment]
@HemulGM Thank you for your proposal! I would like to add it to this awesome list and add you as a contributor due to the information you have provided. Could you please write the library information on line 1042 of [README.md](https://github.com/taishi-i/awesome-ChatGPT-repositories/blob/1d06031ca0436482bfb7990bbd223ece41bf6cd3/README.md?plain=1#L1042) and send a pull request? I will merge it promptly and make it multilingual!

```
1042: * [DelphiOpenAI](https://github.com/HemulGM/DelphiOpenAI) - OpenAI API client for Delphi. Use ChatGPT, DALL-E and other products.
1043: * [ChatGPT](https://github.com/HemulGM/ChatGPT) - Delphi Chat GPT
1044: 
1045: |Name|Language|License|GitHub Stars|
```

If you don't need to be a contributor, just say the word and I'll add you to the list. Thank you!

**Comment by HemulGM** [comment]
Sure, thanks) Only a little later.

**Comment by taishi-i** [comment]
Based on the information provided, I have published the repository. I have also translated it into multiple languages.
 
https://github.com/taishi-i/awesome-ChatGPT-repositories/blob/34c4ffadee112429b0ec3ba399467e9ebe2d8f34/README.md?plain=1#L32

https://github.com/taishi-i/awesome-ChatGPT-repositories/blob/34c4ffadee112429b0ec3ba399467e9ebe2d8f34/README.md?plain=1#L45

If you have a website you would like to promote and would like to be added as a contributor, please edit the following line and send a pull request. Thank you in advance.

https://github.com/taishi-i/awesome-ChatGPT-repositories/blob/34c4ffadee112429b0ec3ba399467e9ebe2d8f34/README.md?plain=1#L56
